// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {module} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Modules():Promise<Array<module.JSModule>>;
