// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['myapp']['App']['Greet'](arg1);
}

export function Modules() {
  return window['go']['myapp']['App']['Modules']();
}
