// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function MyChan(arg1:string):Promise<void>;

export function MyFunc(arg1:string):Promise<string>;

export function SuperFunc2():Promise<string>;
